name: Commit Checks
on: 
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  Pull-Request-Checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Use Node 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run test-cov --if-present
      - run: npm run lint
      - run: npm run pretty-check --if-present
